project_id = "mdokdfljnruitfnnmkif"
[functions.hash-link-password]
enabled = true
verify_jwt = true
import_map = "./functions/hash-link-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hash-link-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hash-link-password/*.html" ]

[functions.verify-link-password]
enabled = true
verify_jwt = true
import_map = "./functions/verify-link-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-link-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-link-password/*.html" ]

[functions.compress-audio]
enabled = true
verify_jwt = true
import_map = "./functions/compress-audio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compress-audio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compress-audio/*.html" ]

[functions.send-pitch-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-pitch-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-pitch-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-pitch-email/*.html" ]

[functions.send-invitation-email]
enabled = true
verify_jwt = true
import_map = "./functions/send-invitation-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-invitation-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-invitation-email/*.html" ]

[functions.log-link-access]
enabled = true
verify_jwt = true
import_map = "./functions/log-link-access/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/log-link-access/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/log-link-access/*.html" ]

[functions.create-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/create-invitation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-invitation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-invitation/*.html" ]

[functions.accept-invitation]
enabled = true
verify_jwt = true
import_map = "./functions/accept-invitation/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accept-invitation/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accept-invitation/*.html" ]

[functions.get-watermarked-audio]
enabled = true
verify_jwt = false
import_map = "./functions/get-watermarked-audio/deno.json"
entrypoint = "./functions/get-watermarked-audio/index.ts"

[functions.send-notification-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-notification-email/deno.json"
entrypoint = "./functions/send-notification-email/index.ts"

[functions.analyze-sonic-dna]
enabled = true
verify_jwt = false
import_map = "./functions/analyze-sonic-dna/deno.json"
entrypoint = "./functions/analyze-sonic-dna/index.ts"

[functions.get-audio-url]
enabled = true
verify_jwt = true
import_map = "./functions/get-audio-url/deno.json"
entrypoint = "./functions/get-audio-url/index.ts"

[functions.log-link-event]
enabled = true
verify_jwt = false
import_map = "./functions/log-link-event/deno.json"
entrypoint = "./functions/log-link-event/index.ts"

[functions.trace-leak]
enabled = true
verify_jwt = true
import_map = "./functions/trace-leak/deno.json"
entrypoint = "./functions/trace-leak/index.ts"

[functions.transcribe-lyrics]
enabled = true
verify_jwt = true
import_map = "./functions/transcribe-lyrics/deno.json"
entrypoint = "./functions/transcribe-lyrics/index.ts"

[functions.send-split-signature]
enabled = true
verify_jwt = true
import_map = "./functions/send-split-signature/deno.json"
entrypoint = "./functions/send-split-signature/index.ts"

[functions.send-executed-splits]
enabled = true
verify_jwt = true
import_map = "./functions/send-executed-splits/deno.json"
entrypoint = "./functions/send-executed-splits/index.ts"

[functions.auto-add-contact]
enabled = true
verify_jwt = false
import_map = "./functions/auto-add-contact/deno.json"
entrypoint = "./functions/auto-add-contact/index.ts"

[functions.smart-ar]
enabled = true
verify_jwt = true
import_map = "./functions/smart-ar/deno.json"
entrypoint = "./functions/smart-ar/index.ts"
