project_id = "mdokdfljnruitfnnmkif"
[functions.hash-link-password]
enabled = true
verify_jwt = true
import_map = "./functions/hash-link-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/hash-link-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/hash-link-password/*.html" ]

[functions.verify-link-password]
enabled = true
verify_jwt = true
import_map = "./functions/verify-link-password/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/verify-link-password/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/verify-link-password/*.html" ]

[functions.compress-audio]
enabled = true
verify_jwt = true
import_map = "./functions/compress-audio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/compress-audio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/compress-audio/*.html" ]
